package com.batescorp.pebble.nav.processor;

/* JADX INFO: loaded from: classes.dex */
public enum NavIconCode {
    IMG_TURN_ARRIVE(1),
    IMG_TURN_DEPART(2),
    IMG_TURN_FORK_LEFT(3),
    IMG_TURN_FORK_RIGHT(4),
    IMG_TURN_GENERIMG_MERGE(5),
    IMG_TURN_GENERIMG_ROUNDABOUT_LEFT(6),
    IMG_TURN_GENERIMG_ROUNDABOUT_RIGHT(7),
    IMG_TURN_LEFT(8),
    IMG_TURN_RAMP_LEFT(9),
    IMG_TURN_RAMP_RIGHT(10),
    IMG_TURN_RIGHT(11),
    IMG_TURN_ROUNDABOUT_1_LEFT(12),
    IMG_TURN_ROUNDABOUT_1_RIGHT(13),
    IMG_TURN_ROUNDABOUT_2_LEFT(14),
    IMG_TURN_ROUNDABOUT_2_RIGHT(15),
    IMG_TURN_ROUNDABOUT_3_LEFT(16),
    IMG_TURN_ROUNDABOUT_3_RIGHT(17),
    IMG_TURN_ROUNDABOUT_4_LEFT(18),
    IMG_TURN_ROUNDABOUT_4_RIGHT(19),
    IMG_TURN_ROUNDABOUT_5_LEFT(20),
    IMG_TURN_ROUNDABOUT_5_RIGHT(21),
    IMG_TURN_ROUNDABOUT_6_LEFT(22),
    IMG_TURN_ROUNDABOUT_6_RIGHT(23),
    IMG_TURN_ROUNDABOUT_7_LEFT(24),
    IMG_TURN_ROUNDABOUT_7_RIGHT(25),
    IMG_TURN_ROUNDABOUT_8_LEFT(26),
    IMG_TURN_ROUNDABOUT_8_RIGHT(27),
    IMG_TURN_ROUNDABOUT_EXIT_LEFT(28),
    IMG_TURN_ROUNDABOUT_EXIT_RIGHT(29),
    IMG_TURN_SHARP_LEFT(30),
    IMG_TURN_SHARP_RIGHT(31),
    IMG_TURN_SLIGHT_LEFT(32),
    IMG_TURN_SLIGHT_RIGHT(33),
    IMG_TURN_STRAIGHT(34),
    IMG_TURN_UTURN_LEFT(35),
    IMG_TURN_UTURN_RIGHT(36),
    IMG_NAVCHEVRON(37),
    IMG_TURN_ARRIVE_RIGHT(38),
    IMG_TURN_ARRIVE_LEFT(39);

    private final int a;

    NavIconCode(int i) {
        this.a = i;
    }

    public int getImageCode() {
        return this.a;
    }
}
